// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njpqipolgxmkvkxzrmcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcHFpcG9sZ3hta3ZreHpybWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTc1ODgsImV4cCI6MjA2NDAzMzU4OH0.OkzYheQcKhgBTM72jzcSDmgFMJQinhJHUVAb4WM264o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);